#!/usr/bin/env bash
# test/plugin-parity.sh — the committed plugin/ tree is generated by
# tools/build-plugin.sh. This check regenerates it to a temp dir and diffs, so a
# hand-edit of plugin/ (or a source change without a rebuild) fails loudly.
#
# Exit 0 = in sync. Exit 1 = drift (run tools/build-plugin.sh and commit).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COMMITTED="$REPO_ROOT/plugin"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if [ ! -d "$COMMITTED" ]; then
    echo "plugin-parity: FAIL — $COMMITTED does not exist; run tools/build-plugin.sh" >&2
    exit 1
fi

bash "$REPO_ROOT/tools/build-plugin.sh" "$TMP/plugin" >/dev/null

if diff -ru "$COMMITTED" "$TMP/plugin" >"$TMP/diff.txt" 2>&1; then
    echo "plugin-parity: OK — plugin/ matches tools/build-plugin.sh output"
    exit 0
fi

echo "plugin-parity: FAIL — plugin/ is stale. Run tools/build-plugin.sh and commit." >&2
echo "--- diff (committed vs freshly built) ---" >&2
cat "$TMP/diff.txt" >&2
exit 1
